# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20181206_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
    ]
