# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='Category',
        ),
    ]
