# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_image_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
    ]
